export type {
  DesktopPlatform,
  AppTargetLaunch,
  AppTargetProcess,
  AppTargetWindow,
  AppTargetReset,
  AppTargetShutdown,
  AppSession,
  DesktopEnvironmentProvider,
  AppTargetErrorCode,
} from "./app-target.js";

export {
  AppTarget,
  validateAppTarget,
  AppTargetError,
  APP_TARGET_LIMITS,
} from "./app-target.js";

export type {
  UiaPattern,
  UiaPatternDescriptor,
  UiaExtensionV1,
  DesktopActionKind,
  DesktopAdapterCapabilities,
  AdapterSupport,
} from "./uia-extension.js";

export {
  UIA_EXTENSION_TYPE,
  UIA_EXTENSION_VERSION,
} from "./uia-extension.js";

export type {
  LocalActionRisk,
  DesktopActionResolution,
  ResolvedDesktopActionBase,
  DesktopValueBinding,
  DesktopPlaintextValue,
  DesktopActionDigestInput,
  ResolvedDesktopAction,
  ResolvedWebAction,
  ResolvedAction,
  LocalPermitAuthorization,
  LocalPermitRequest,
  LocalApprovalStatus,
  LocalApprovalDecision,
  LocalExecutionPermit,
  CompanionUiaSourceBounds,
  CompanionUiaSourceNode,
  CompanionUiaSource,
  LocalActionOutcomeReport,
  CompanionRequestPayloadByType,
  CompanionRequestType,
  CompanionRequestEnvelope,
  CompanionRequest,
  CompanionHandshakeChallenge,
  CompanionHandshakeAccepted,
  CompanionSessionResponsePayload,
  CompanionAppLifecyclePayload,
  CompanionResponsePayloadByType,
  CompanionResponseType,
  ExpectedCompanionResponseType,
  CompanionOkResponse,
  CompanionStableErrorCode,
  CompanionStableError,
  CompanionErrorResponse,
  CompanionResponse,
  CompanionProofSignatureAlgorithm,
  CompanionIpcErrorCode,
  CompanionProofBytesInput,
  LocalAuthorizationClass,
} from "./companion-ipc.js";

export {
  COMPANION_REQUEST_TYPES,
  COMPANION_RESPONSE_TYPES,
  COMPANION_IPC_LIMITS,
  PROTOCOL_MAJOR,
  COMPANION_PROOF_CONTEXT,
  COMPANION_UIA_PASSWORD_MASK_VALUE,
  CompanionIpcError,
  assertDeclaredFrameLength,
  parseResolvedDesktopAction,
  parseDesktopValueBinding,
  desktopValueBindingForPlaintext,
  parseDesktopPlaintextValue,
  assertDesktopValueBindingMatchesAction,
  desktopActionDigestSha256,
  parseLocalPermitAuthorization,
  parseLocalExecutionPermit,
  parseLocalPermitRequest,
  parseCompanionDecision,
  parseLocalActionOutcomeReport,
  parseCompanionUiaSource,
  expectedResponseTypeForRequest,
  createCompanionRequestEnvelope,
  parseCompanionStableError,
  parseCompanionResponse,
  buildCompanionProofBytes,
  parseCompanionRequest,
  classifyLocalAuthorization,
  isLocalPermitExpired,
} from "./companion-ipc.js";
